use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'



target 'AHFMFeature_Example' do
  pod 'AHFMFeature', :path => '../'

pod 'AHServiceRouter'

pod 'AHFMDataCenter'
pod 'AHFMNetworking'
pod 'AHFMDataTransformers'

pod 'AHFMServices'
pod 'AHFMModuleManager'

pod 'AHFMFeatureServices'
pod 'AHFMFeatureManager'

pod 'AHFMDownloaderManager'

pod 'AHFMShowPage'
pod 'AHFMShowPageManger'
pod 'AHFMShowPageServices'

pod 'AHAudioPlayer'
pod 'AHFMAudioPlayerManager'

pod 'AHFMDownloadCenter'
pod 'AHFMDownloadCenterManager'

pod 'AHFMDownloadList'
pod 'AHFMDownloadListManager'
pod 'AHFMDownloadListServices'

pod 'AHFMAudioPlayerVC'
pod 'AHFMAudioPlayerVCManager'
pod 'AHFMAudioPlayerVCServices'

pod 'AHFMEpisodeListVC'
pod 'AHFMEpisodeListVCManager'

pod 'AHFMHistoryVC'
pod 'AHFMHistoryVCManager'

pod 'AHFMEpisodeListVC'
pod 'AHFMAudioPlayerManager'

pod 'AHFMBottomPlayer'
pod 'AHFMBottomPlayerManager'
pod 'AHFMBottomPlayerServices'
  
  
  target 'AHFMFeature_Tests' do
    inherit! :search_paths

    
  end
end
